# Utilisation de l'image Python officielle comme base
FROM python:3.9-slim

# Définition du répertoire de travail dans le conteneur
WORKDIR /app

# Copie du fichier requirements.txt contenant les dépendances
COPY requirements.txt .

# Installation des dépendances
RUN pip install --no-cache-dir -r requirements.txt

# Copie du code source de l'application dans le conteneur
COPY . .

# Commande de démarrage pour exécuter l'application avec Flask
CMD ["python", "app.py"]
